INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Chanel Watch', 'Tampines',30,80,1,7,3,'2018-10-20',7 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Gucci Bag', 'Bishan',10,20,2,2,2,'2018-11-12','14' ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Nike Shoes', 'Novena',30,30,3,1,1,'2018-10-25',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Daniel Wallington Watch', 'Bugis',30,80,4,1,1,'2018-11-25',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Notebook', 'Kallang',10,20,5,15,10,'2018-12-30',21 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Thumbdrive', 'Aljunied',10,60,6,1,1,'2018-12-29',21 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Denim Jacket', 'Sengkang',20,50,7,1,1,'2018-12-19',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Beats Headphones', 'Ubi',20,20,8,10,5,'2018-04-30',7 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Facial Wash', 'Harbourfront',60,100,9,15,15,'2018-10-10',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('A&F Perfume', 'Somerset',10,10,10,1,1,'2018-12-25',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Boy London Pullover', 'Redhill',60,120,11,20,5,'2018-11-06',21 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Champion Shirt', 'Kranji',10,90,12,1,1,'2018-11-25',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Boxers', 'Khatib',10,10,13,1,1,'2018-11-25',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Kate Spade Keychain', 'Yishun',60,80,14,4,2,'2018-12-30',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Limited Edition Notebooks', 'Woodlands',10,100,15,20,1,'2018-12-30',21 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Gucci Slippers', 'Marymount',50,50,16,2,1,'2018-10-19',21 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Caps', 'Newton',20,120,17,1,1,'2018-10-02',7) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Forever21 Hoodie', 'Kovan',10,150,18,20,20,'2018-11-01',14) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Cotton On Dress', 'Punggol',50,50,19,3,3,'2018-12-12',21 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Pencil Case', 'Eunos',60,60,20,1,1,'2018-11-25',7 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Wallet', 'Yishun',40,50,1,15,0,'2018-12-15',7) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Kate Spade Bag', 'Tampines',20,20,2,8,0,'2018-11-09',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Apple Earpiece', 'Sembawang',20,20,3,1,1,'2018-12-15',21) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Dress', 'Khatib',30,80,4,7,3,'2018-12-09',7 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Hairband', 'Macpherson',20,20,5,1,1,'2018-12-20',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Scarf', 'Bedok',50,80,6,20,0,'2018-12-19',14) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Lipgloss', 'Bugis',60,200,7,7,7,'2018-12-17',7) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Camera', 'Eunos',30,120,8,2,0,'2018-12-13',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Converse Shoes', 'Bradell',10,120,9,1,1,'2018-11-13',21 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Sandals', 'Cashew',60,80,10,7,7,'2018-10-12',21 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Notebooks', 'Stadium',50,50,11,5,5,'2018-10-15',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Iphone cable', 'Bishan',30,50,12,3,3,'2018-11-13',7) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Kate Spade Wallet', 'Orchard',80,180,13,8,1,'2018-11-18',21 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Body Shop Handsoap', 'Tampines',20,20,14,1,0,'2018-12-12',21) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Pencil Case', 'Bradell',10,10,15,1,1,'2018-11-10',7 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration)VALUES ('Beats Headphones', 'Somerset',30,100,16,20,2,'2018-11-22',14) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Sandals', 'Tampines',40,50,17,3,3,'2018-11-19',21 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Adidas Shoes', 'Bencoolen',50,80,18,7,3,'2018-12-03',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Nike Shoes', 'Esplanade',60,80,19,1,1,'2018-12-01',7 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Headphones', 'Redhill',20,50,20,1,0,'2018-12-01',7 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Champion Hoodie', 'Dover',60,80,1,1,1,'2018-11-21',21 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Perfume', 'Clementi',50,50,2,1,0,'2018-10-16',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Starbucks Tumblr', 'Jurong',60,80,3,50,40,'2018-12-14',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Starbucks Notebook', 'Bishan',30,80,4,7,3,'2018-10-13',7 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Victoria Secret Wallet', 'Punggol',50,80,5,2,0,'2018-12-19',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Dress', 'Redhill',20,190,6,140,10,'2018-12-20',21 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Iphone Cover', 'Tampines',20,30,7,3,0,'2018-12-12',21) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Camera', 'Bedok',90,190,8,80,2,'2018-10-08',14 ) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Converse Shoes', 'Bishan',20,60,9,1,0,'2018-11-30',21) ;
INSERT INTO entry (name,location,starting_bid,current_bid,owner_id,total_quantity,current_quantity,bid_closing_date,loan_duration) VALUES ('Nike Shoes', 'Cashew',50,50,10,1,0,'2018-12-30',7 ) ;
